apiVersion: resourcemanager.yandex-cloud.jet.crossplane.io/v1alpha1
kind: Folder
metadata:
  name: default
  annotations:
    crossplane.io/external-name: "b1glisnpgipkm8suavcm"
spec:
  deletionPolicy: Orphan
  forProvider:
    name: default
---
kind: Network
apiVersion: vpc.yandex-cloud.jet.crossplane.io/v1alpha1
metadata:
  name: default
  annotations:
    crossplane.io/external-name: "enpe14qb85scv9lpdhq3"
spec:
  deletionPolicy: Orphan
  forProvider:
    name: default
    folderIdRef:
      name: default
---
kind: Zone
apiVersion: dns.yandex-cloud.jet.crossplane.io/v1alpha1
metadata:
  name: yc-courses
  annotations:
    crossplane.io/external-name: "dns93qmhrij0h7bj1t8k"
spec:
  deletionPolicy: Orphan
  forProvider:
    name: yc-courses
    zone: "yc-courses.ga."
    public: true
    folderIdRef:
      name: default
---
kind: Subnet
apiVersion: vpc.yandex-cloud.jet.crossplane.io/v1alpha1
metadata:
  name: default-ru-central1-b
  annotations:
    crossplane.io/external-name: "e2lfmpcj1gai7sl4243j"
spec:
  forProvider:
    networkIdRef:
      name: default
    folderIdRef:
      name: default
    v4CidrBlocks:
      - 10.129.0.0/24
