# Создаем неймспейс для gitlab-runner
apiVersion: v1
kind: Namespace
metadata:
  name: httpbin
  annotations:
    # С помощью этого параметра указываем порядок создания
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: httpbin
  # Обратите внимание на namespace – он должен быть argocd
  namespace: argocd
spec:
  destination:
    # А вот тут уже неймспейс, куда будет устанавливаться сам чарт
    namespace: httpbin
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    # Указываем путь до чарта
    path: charts/httpbin
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    # Указываем путь до файла
    helm:
      valueFiles:
        - secrets+age-import:///helm-secrets-private-keys/key.txt?../../values/httpbin.yaml
  syncPolicy:
    automated: {}
